name: Test action

on:
  push:
    branch: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS_BASE64 }}
        target: test/test.txt
        parent_folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
